[package]
name = "cargo-wiki"
authors = ["Aditya Kumar <git@adityais.dev>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
rustdoc-types = "0.33"
serde_json = "1"